defaultContentLanguage: ru
minifyOutput: true
enableRobotsTXT: true
disableKinds:
  - section
  - taxonomy
  - term
  - RSS

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  editURL: https://github.com/wault-pw/landing/blob/master/content/
  dnsPrefetch: http://a.lvh.me:1313,http://b.lvh.me:1313
  preconnect: http://b.lvh.me:1313,http://c.lvh.me:1313
  loginURL: http://localhost:3000/
  joinURL: http://localhost:3000/#/join

languages:
  en:
    baseURL: /
    cdnURL: ""
    yandexMetrics:
    googleAnalytics:
    email: support@wault.pw
    title: Wault password manager
    description: Wault can store passwords and other confidential data from credit card PIN codes to private notes. You can get access to your data from anywhere and from any device, including your smartphone. You don’t need to download, install, and update anything. And with offline version of Wault, your most precious data will be at hand all the time, even when you don’t have Internet connection.
    copyright: Wault
    location: AWS
    menu:
      header:
        - name: Features
          weight: 20
          url: /features/overview/
        - name: Security
          weight: 40
          url: /security/overview/
        - name: Source code
          weight: 50
          url: /source/
      footer:
        - weight: 10
          name: Terms
          url: /legal/terms/
        - weight: 20
          name: Privacy
          url: /legal/privacy/
        - weight: 30
          name: GitHub
          url: https://github.com/wault-pw
        - weight: 40
          name: Status
          url: https://stats.uptimerobot.com/lV4X9c1gRN

  ru:
    baseURL: /
    cdnURL: ""
    yandexMetrics:
    googleAnalytics:
    email: support@example.com
    description: Wault может хранить пароли и любые другие конфиденциальные данные, от PIN-кодов кредитных карт до личных заметок. Вы можете получить доступ к своим данным из любого места и с любого устройства, включая ваш смартфон. Нечего скачивать, устанавливать и обновлять. А с офлайн-версией Wault ваши самые ценные данные всегда под рукой, даже когда нет подключения к Интернет.
    title: Wault менеджер паролей
    copyright: Wault
    location: Yandex.Cloud
    menu:
      header:
        - name: Возможности
          weight: 20
          url: /features/overview/
        - name: Безопасность
          weight: 40
          url: /security/overview/
        - name: Исходный код
          weight: 50
          url: /source/
      footer:
        - weight: 10
          name: Правила пользования
          url: /legal/terms/
        - weight: 20
          name: Конфидециальность
          url: /legal/privacy/
        - weight: 30
          name: GitHub
          url: https://github.com/wault-pw
        - weight: 40
          name: Статус
          url: https://stats.uptimerobot.com/4Dn8VizL95

  zh:
    baseURL: /
    cdnURL: ""
    yandexMetrics:
    googleAnalytics:
    email: support@example.com
    description: Wault可以存储来自信用PIN码的密码和任何其他敏感数据。至个人笔记。您可以从任何地方和任何设备访问您的数据，
    title: Wault密码管理器
    copyright: Wault
    location: Yandex.Cloud
    menu:
      header:
        - name: 可能性
          weight: 20
          url: /features/overview/
        - name: 安全
          weight: 40
          url: /security/overview/
        - name: 源代码
          weight: 50
          url: /source/
      footer:
        - weight: 10
          name: 使用条款
          url: /legal/terms/
        - weight: 20
          name: 隐私性
          url: /legal/privacy/
        - weight: 30
          name: GitHub
          url: https://github.com/wault-pw
        - weight: 40
          name: 状态
          url: https://stats.uptimerobot.com/4Dn8VizL95
